#!/bin/sh

# To activate this hook, use:
# git config --local core.hooksPath .githooks

echo "Running FusionDLS pre-commit hook..."

caveat="If you really know what you're doing, commit again with --no-verify"

which ruff
if [ $? != "0" ]; then
  echo "ruff is not installed, please install it with 'pip install ruff'"
  echo caveat
  exit 1
fi

echo "Formatting..."
ruff format

echo "Linting..."
ruff check
if [ $? != "0" ]; then
  echo "Found linter errors, fix all reported by 'ruff check' and try again."
  echo "Hint: you may be able to fix some using 'ruff check --fix'."
  echo $caveat
  exit 1
fi

which pytest
if [ $? != "0" ]; then
  echo "pytest is not installed, please install it with 'pip install pytest'"
  echo $caveat
  exit 1
fi

echo "Testing..."
pytest
if [ $? != "0" ]; then
  echo "Tests are failing, fix all failing tests and try again."
  echo $caveat
  exit 1
fi